cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.05319149
  brandStrength: 0.9829787
  lightness: 0.7021276
  brandColors:
    - '#E1F0FB'
    - '#01020D'
    - '#789954'
    - '#425330'
    - '#C56644'
  rhythmicContrast: 0.2702128
typography_spectrum: 0.2042553
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: muthking
